const u = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=70`;
// Editorial destination content. Trip counts and trips always come from the database.
export const DESTINATIONS = [
  { slug: 'goa', name: 'Goa', state: 'Goa', latitude: 15.2993, longitude: 74.124, image: u('photo-1512343879784-a960bf40e7f2'), blurb: 'Beaches, cafés and old Portuguese lanes.', description: 'Goa mixes lively beaches in the north with quiet coves and heritage villages in the south. Groups love it for shared villas and scooter days.', activities: ['Beach hopping', 'Water sports', 'Old Goa heritage walk', 'Night markets'] },
  { slug: 'manali', name: 'Manali', state: 'Himachal Pradesh', latitude: 32.2396, longitude: 77.1887, image: u('photo-1626621341517-bbf3d9990a23'), blurb: 'Snow passes, pine valleys and river camps.', description: 'A gateway to the Pir Panjal range with Solang Valley, Rohtang Pass and easy treks for first-timers.', activities: ['Solang Valley', 'Rohtang Pass', 'River rafting', 'Hadimba temple'] },
  { slug: 'jaipur', name: 'Jaipur', state: 'Rajasthan', latitude: 26.9124, longitude: 75.7873, image: u('photo-1477587458883-47145ed94245'), blurb: 'Forts, palaces and bazaars in pink stone.', description: 'The Pink City packs Amer Fort, City Palace and Hawa Mahal into a walkable heritage circuit.', activities: ['Amer Fort', 'City Palace', 'Bazaar food walk', 'Sunset at Nahargarh'] },
  { slug: 'kashmir', name: 'Kashmir', state: 'Jammu & Kashmir', latitude: 34.0837, longitude: 74.7973, image: u('photo-1595815771614-ade9d652a65d'), blurb: 'Houseboats, meadows and alpine lakes.', description: 'Dal Lake shikaras, Gulmarg gondolas and the Great Lakes trek make Kashmir a favorite for scenic group trips.', activities: ['Dal Lake shikara', 'Gulmarg', 'Pahalgam', 'Mughal gardens'] },
  { slug: 'rishikesh', name: 'Rishikesh', state: 'Uttarakhand', latitude: 30.0869, longitude: 78.2676, image: u('photo-1600100397608-f010f423b971'), blurb: 'Rafting, yoga and Ganga aarti.', description: 'Adventure and calm side by side: white-water rafting, bungee, riverside camps and sunrise yoga.', activities: ['River rafting', 'Camping', 'Yoga', 'Ganga aarti'] },
  { slug: 'ladakh', name: 'Ladakh', state: 'Ladakh', latitude: 34.1526, longitude: 77.5771, image: u('photo-1506905925346-21bda4d32df4'), blurb: 'High passes, monasteries and Pangong blue.', description: 'Road trips over Khardung La, monasteries in Hemis and Thiksey, and the shifting blues of Pangong Tso.', activities: ['Pangong Tso', 'Nubra Valley', 'Monastery visits', 'Bike road trip'] },
  { slug: 'kerala', name: 'Kerala', state: 'Kerala', latitude: 9.4981, longitude: 76.3388, image: u('photo-1602216056096-3b40cc0c9944'), blurb: 'Backwaters, tea hills and slow travel.', description: 'Houseboats in Alleppey, tea gardens in Munnar and beaches in Varkala — best done at an unhurried pace.', activities: ['Houseboat stay', 'Munnar tea gardens', 'Varkala cliff', 'Kathakali show'] },
  { slug: 'himachal-pradesh', name: 'Himachal Pradesh', state: 'Himachal Pradesh', latitude: 31.1048, longitude: 77.1734, image: u('photo-1605649487212-47bdab064df7'), blurb: 'Hill towns, treks and apple valleys.', description: 'From Kasol cafés to Spiti\'s cold desert, Himachal has routes for every kind of group.', activities: ['Kasol & Kheerganga', 'Spiti Valley', 'Shimla', 'Triund trek'] },
  { slug: 'meghalaya', name: 'Meghalaya', state: 'Meghalaya', latitude: 25.467, longitude: 91.3662, image: u('photo-1626714485822-5e2b2d1b6b0b'), blurb: 'Living root bridges and clear rivers.', description: 'Cherrapunji waterfalls, Dawki\'s glass-clear river and the double-decker root bridge.', activities: ['Living root bridges', 'Dawki river', 'Cave exploring', 'Shillong cafés'] }
];
export const findDestination = (slug) => DESTINATIONS.find(d => d.slug === slug);
